[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./number.txt"}]

[rpc_endpoints]
anvil = "127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}" 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
